package chikoski:advent-of-spin@0.2.0;

interface naughty-or-nice-calculatorable {
    record score {
        name: string,
        score: u32,
    }
    calculate: func(name: string) -> score;
}

world naughty-or-nice-calculator {
    export naughty-or-nice-calculatorable;
}